name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Railway
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: Deploy
        run: npx railway up --service livestatus
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
